$(document).ready(function(){
var c_words =["法定继承",
"法定继承人",
"法定监护人",
"利率",
"量刑规则",
"债务关系",
"法官",
"公正的法官",
"法规",
"根据法规",
"法条竞合",
"法理学",
"按照法律",
"有追溯力的法律",
"法律上有效的",
"法律保护",
"法律地位",
"法律顾问",
"法律汇编",
"法律关系",
"回溯力",
"法律救济",
"法律后果",
"法律漏洞",
"有意识的法律漏洞",
"法律面前人人平等",
"生效",
"胜诉",
"失效",
"实用新型",
"注册",
"失效",
"世界格局",
"世界经济秩序",
"世贸体系",
"事实",
"事实婚姻关系",
"征税",
"收养",
"收养的",
"受教育权",
"受教育的义务",
"税",
"税率",
"司法",
"司法部",
"溯及既往的",
"诉讼代理人",
"诉讼当事人",
"诉讼的",
"特权",
"授予特权",
"调解",
"调解程序",
"通货膨胀",
"外汇",
"违法的",
"违法",
"违法行为",
"违法者",
"违反合同",
"违反合同的",
"违宪的",
"委托",
"委托合同",
"未成年人",
"未成年",
"未成年的",
"行为能力",
"未成年人保护",
"无限制的",
"物权",
"吸毒",
"毒品",
"嫌疑",
"宪法",
"现行规定",
"消费",
"消费者",
"消费者保护法",
"小偷",
"协议",
"薪金",
"行政机关",
"行政监督",
"行政法规",
"行政诉讼",
"刑事判决",
"许可证",
"宣告无罪",
"选举",
"选举权",
"遗产",
"遗嘱",
"银行储备金",
"有效的",
"有效期",
"诈骗",
"债权",
"债",
"债务关系",
"债权人",
"债务人",
"章程",
"肇事司机",
"征税",
"争端",
"证据",
"证据保全",
"证券",
"支票",
"殖民地",
"执行机关",
"仲裁",
"重罪",
"登记注册",
"注销",
"著作权",
"著作权的",
"专利",
"专利法",
"转让",
"状况",
"追溯力",
"资本",
"资产负债表",
"资金",
"钻法律的空子",
"罪行",
"最低费用",
"最高法院",
"最高检察院",
"最高立法机关",
"最惠国",
"最惠国待遇",
"遵守合同",
"作为和不作为",
"盗版",
"盗版活动",
"盗版者",
"普通法(英美法)",
"衡平法"]
 var g_words =["gesetzliche Beerbung ",
 "gesetzlicher Erbe, Noterbe, Intestaterbe ",
 "gesetzlicher Vormund",
 "Zinsfuß, Zinssatz",
 "Strafzumessungsregel",
 "Schuldverhältnis ",
 "Richter, Gerichtsbeamter ",
 "unvoreingenommener Richter ",
 "Gesetzesverordnung, Statut n., Verordnung, Rechtsnorm f.",
 "laut Vorschriften ",
 "Gesetzeskonkurrenz f.",
 "Juristerei f., Jurisprudenz f., Rechtsphilosophie f. ",
 "nach dem (geltenden) Recht oder Gesetz, gesetzmäßig ",
 "rückwirkendes Gesetz, Gesetz mit rückwirkender Kraft",
 "rechtkräftig, rechtswirksam, rechtsgültig ",
 "Rechtsschutz m. ",
 "Rechtsstand, die rechtliche Stellung ",
 "Rechtsberater, Justizrat, Rechtsratgeber, Rechtsbeistand, Rechtskonsulent",
 "Gesetzessammlung",
 "Rechtsverhältnis, Rechtsbeziehung, Rechtsverkehr",
 "Rückwirkung von Gesetz ",
 "Rechtsbehelf m., Rechtshilfe ",
 "Rechtsfolge, Rechtswirkung ",
 "Gesetzlücke, Lücke in Gesetz",
 "bewusste Rechtslücke ",
 "Gleichheit vor dem Gesetz ",
 "in Kraft setzen, in Kraft treten, in Wirksamkeit treten",
 "erfolgreich klagen ",
 "außer Kraft treten",
 "Geschmacksmuster n. ",
 "registrieren ",
 "Verjährung ",
 "Weltgefüge n. ",
 "Weltwirtschaftsordnung  WTO Welthandelsorganisation",
 "Welthandelssystem, internationales Handelssystem",
 "Tatsache f., Tat f., Realität f. ",
 "eheähnliches Verhältnis ",
 "Steuereinziehung, Steuereinnahme ",
 "Adoption, Kindesannahme ",
 "adoptiv ",
 "Recht auf Bildung",
 "Schulpflicht",
 "Steuer f., Abgabe",
 "Steuersatz m., Hebesatz ",
 "Justiz f.",
 "Justizministerium ",
 "zurückbezogen ",
 "Prozessvertreter, Prozessagent, Prozessbeistand ",
 "Prozesspartei, Prozessführender, Prozessführer",
 "gerichtlich ",
 "Privileg n., Sonderrecht",
 "privilegieren ",
 "Vergleich m., vergleichen ",
 "Vergleichsverfahren ",
 "Inflation f.",
 "Devisen pl. ",
 "gesetzwidrig, unrechtlich ",
 "Rechtswidrigkeit, gegen das Gesetz verstoßen ",
 "Delikt n., Delikthandlung, rechtswidriges Verhalten, rechtswidrige Tat ",
 "Gesetzübertreter, Rechtsbrecher",
 "Verstoß gegen einen Vertrag, Vertragsbruch, Vertragsverstoß, Vertragswidrigkeit",
 "kontraktwidrig, vertragswidrig, vertragsbrüchig ",
 "verfassungsfeindlich",
 "Beauftragung, Auftrag ",
 "Auftragsvertrag ",
 "Unmündiger, Minderjähriger",
 "Minderjährigkeit",
 "minderjährig, unmündig",
 "Geschäftsfähigkeit, Handlungsfähigkeit ",
 "Minderjährigenschutz",
 "unbegrenzt, unbeschränkt ",
 "Sachenrecht ",
 "Rauschgift nehmen",
 "Rauschgift n., Droge f. ",
 "verdächtigen, Verdächtigung",
 "Staatsverfassung, Verfassungsrecht, Grundgesetz",
 "die derzeitige Regelung",
 "Konsum m.",
 "Konsument m., Verbraucher ",
 "Verbraucherschutzgesetz, Konsumenchutz-Gesetz",
 "Stehler, Dieb n. ",
 "Vereinbarung, Übereinkommen, Vertrag",
 "Gehalt n. ",
 "Verwaltungsorgan n., Verwaltungsapparat m. ",
 "Verwaltungsaufsicht f.",
 "die administrativen Verordnungen",
 "verwaltungsrechtliche Streitigkeit, Verwaltungsbeschwerde, Verwaltungsklage",
 "Strafurteil n. Strafrechtliche Beurteilung ",
 "Erlaubnisurkunde, Erlaubnisschein ",
 "freisprechen, Freisprechung ",
 "Wahl f.",
 "Wahlrecht ",
 "Erbe f., Erbschaft",
 "Testament n.",
 "Bankreserve f., Bankrücklage ",
 "rechtskräftig, rechtswirksam",
 "Laufzeit",
 "beschwindeln, betrügen, Beschwindel m., Betrug m. ",
 "Schuldforderung, obligatorisches Recht, obligatorischer Anspruch ",
 "Schuld f. ",
 "Schuldverhältnis, Anleiheverhältnis ",
 "Schuldforderungsherr, Gläubiger, Kreditor, Berechtiger ",
 "Debitor, Schuldner ",
 "Satzung, Statut n., Konstitution ",
 "Unfallfahrer ",
 "Steuer erheben, eintreiben, einziehen",
 "Streitigkeit, Streit, Streitfall, streitige Angelegenheit ",
 "Beweis m., Beweisgrund m., Beweismittel f.",
 "Beweissicherung ",
 "Aktienpapier, Wertpapier",
 "Scheck m., Anweisungsschein ",
 "Kolonie f. ",
 "Ausführungsorgan, Ausführungsbehörde ",
 "Schiedsspruch m., Schiedsgerichtsbarkeit, Arbitrage, Schlichtung, Interzession",
 "schweres Verbrechen ",
 "Anmeldung, Eintragung, Registrierung",
 "Abmeldung ",
 "Urheberrecht , Autorenrecht ",
 "urheberrechtlich ",
 "Patent ",
 "Patentrecht, Patengesetz",
 "Übertragung",
 "Position f., Status m., Zustand m., Lage ",
 "Zurückwirkung ",
 "Kapital m., Substanz f. ",
 "Bilanz f.",
 "Mittel f., Finanzmittel, Geldmittel",
 "durch eine Lücke des Gesetzes schlüpfen ",
 "Straftat f., Tat ",
 "Mindestgebühr ",
 "oberster Gerichtshof, oberstes Gericht",
 "die Oberste Volksstaatsanwaltschaft ",
 "die oberste Gesetzgebungsorgan",
 "meistbegünstigter Staat ",
 "Meistbegünstigung ",
 "Einhaltung eines Vertrages, einen Vertrag einhalten ",
 "Handlungen und Unterlassungen, Tun und Unterlassung ",
 "Raubkopie f., Raubdruck m.",
 "Aktivitäten von unerlaubtem Nachdruck ",
 "Pirat m. ",
 "Gemeinrecht, gemeines Recht, generelles Recht, allgemeines Recht ",
 "Billigkeitsrech"]

notice =[
"怎么又错啦~",
"加油啊加油~",
"都不知道怎么说你了~",
"是不是没有认真复习啊~",
"好想吃烤鸭啊，额，好像和背单词没关系~",
"今天冷不冷啊，不要冻到了~",
"输赢乃兵家常事，大侠请从新来过~",
"就是任性，错了又怎么样~",
"看电视去了，慢慢背单词~",
"想开点~"
]
var correct_num = 0
var wrong_num =0
var num = Math.floor((Math.random() * 142));
var pic_num = Math.floor((Math.random() * 8)+1);
init(num)
$("#submit").click(function(e){
  check(num,pic_num)
  num = Math.floor((Math.random() * 142));
  pic_num = Math.floor((Math.random() * 8)+1);
  $("#display").html(g_words[num])
   console.log(c_words[num])
    $("#input").val("")
  })

function check(num,pic_num){
  var enter = $("#input").val()
  var correct = false
  if (enter == c_words[num]){
    correct =true
  }
    
  if (correct){
    correct_num+=1
    $("#display_correct").html(correct_num)
    $("#image").attr("src","pic/c"+pic_num+".jpeg")

  }else{
    wrong_num+=1
    $("#display_wrong").html(wrong_num)
    $("#image").attr("src","pic/w"+pic_num+".jpeg")
    var  notice_num = Math.floor((Math.random() * 10));
    console.log(notice_num)
    $("#notice").html(notice[notice_num])
    $("#wrong-list").append("<p>"+wrong_num+": "+c_words[num]+" "+g_words[num]+"</p>")
  }
}
function init(num){
  $("#display").html(g_words[num])
   console.log(c_words[num])
}



});
